module CitiesFactory

  #california
  City.create(city_name: 'San Francisco', state: 'California', country: "United States")
  City.create(city_name: 'Daly City', state: 'California', country: "United States")
  City.create(city_name: 'South San Francisco', state: 'California', country: "United States")
  City.create(city_name: 'Sausalito', state: 'California', country: "United States")
  City.create(city_name: 'Marin City', state: 'California', country: "United States")
  City.create(city_name: 'Mill Valley', state: 'California', country: "United States")
  City.create(city_name: 'San Rafael', state: 'California', country: "United States")
  City.create(city_name: 'Richmond', state: 'California', country: "United States")
  City.create(city_name: 'Albany', state: 'California', country: "United States")
  City.create(city_name: 'Berkeley', state: 'California', country: "United States")
  City.create(city_name: 'Pinole', state: 'California', country: "United States")
  City.create(city_name: 'Crockett', state: 'California', country: "United States")
  City.create(city_name: 'Vallejo', state: 'California', country: "United States")
  City.create(city_name: 'Martinez', state: 'California', country: "United States")
  City.create(city_name: 'Concord', state: 'California', country: "United States")
  City.create(city_name: 'Walnut Creek', state: 'California', country: "United States")
  City.create(city_name: 'Lafayette', state: 'California', country: "United States")
  City.create(city_name: 'Danville', state: 'California', country: "United States")
  City.create(city_name: 'San Leandro', state: 'California', country: "United States")
  City.create(city_name: 'Oakland', state: 'California', country: "United States")
  City.create(city_name: 'Alameda', state: 'California', country: "United States")
  City.create(city_name: 'Emeryville', state: 'California', country: "United States")
  City.create(city_name: 'Piedmont', state: 'California', country: "United States")
  City.create(city_name: 'San Mateo', state: 'California', country: "United States")
  City.create(city_name: 'Palo Alto', state: 'California', country: "United States")
  City.create(city_name: 'Menlo Park', state: 'California', country: "United States")
  City.create(city_name: 'Belmont', state: 'California', country: "United States")
  City.create(city_name: 'Foster City', state: 'California', country: "United States")
  City.create(city_name: 'Milbrae', state: 'California', country: "United States")
  City.create(city_name: 'Pacifica', state: 'California', country: "United States")
  City.create(city_name: 'Mountain View', state: 'California', country: "United States")
  City.create(city_name: 'Sunnyvale', state: 'California', country: "United States")
  City.create(city_name: 'Milpitas', state: 'California', country: "United States")
  City.create(city_name: 'Fremont', state: 'California', country: "United States")
  City.create(city_name: 'Union City', state: 'California', country: "United States")
  City.create(city_name: 'Hayward', state: 'California', country: "United States")
  City.create(city_name: 'Newark', state: 'California', country: "United States")
  City.create(city_name: 'Pleasanton', state: 'California', country: "United States")
  City.create(city_name: 'Livermore', state: 'California', country: "United States")
  City.create(city_name: 'Santa Clara', state: 'California', country: "United States")
  City.create(city_name: 'San Jose', state: 'California', country: "United States")
  City.create(city_name: 'Santa Cruz', state: 'California', country: "United States")
  City.create(city_name: 'Gilroy', state: 'California', country: "United States")
  City.create(city_name: 'San Luis Obispo', state: 'California', country: "United States")
  City.create(city_name: 'Bakersfield', state: 'California', country: "United States")
  City.create(city_name: 'Santa Barbara', state: 'California', country: "United States")
  City.create(city_name: 'Los Angeles', state: 'California', country: "United States")
  City.create(city_name: 'Santa Monica', state: 'California', country: "United States")
  City.create(city_name: 'San Diego', state: 'California', country: "United States")
  City.create(city_name: 'La Jolla', state: 'California', country: "United States")


  # within SF
  City.create(city_name: 'Outer Richmond District, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Richmond District, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Laurel Heights, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Outer Sunset, San Francisco, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Inner Sunset, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Forest Hill, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Mission District, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Financial District, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Mission Bay, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Haight-Ashbury, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Castro District, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Dogpatch, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Bernal Heights, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Noe Valley, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Russian Hill, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: 'Japantown, San Francisco', state: 'California', country: 'United States')
  City.create(city_name: "Presidio Heights, San Francisco", state: "California", country: "United States")
  City.create(city_name: "Jordan Park, San Francisco", state: "California", country: "United States")
  City.create(city_name: "Laguna Heights, San Francisco", state: "California", country: "United States")
  City.create(city_name: "Nob Hill, San Francisco", state: "California", country: "United States")
  City.create(city_name: "Twin Peaks, San Francisco", state: "California", country: "United States")
  City.create(city_name: "Glen Park, San Francisco", state: "California", country: "United States")
  City.create(city_name: "Excelsior, San Francisco", state: "California", country: "United States")

  # Easy Bay
end
